name: 'Slack Release Notification'
description: 'A GitHub Action to send Slack notifications for release pull requests'
inputs:
  slack-bot-token:
    description: 'Slack bot token'
    required: true
  slack-channel:
    description: 'Slack channel ID'
    required: true
  github-token:
    description: 'GitHub token'
    required: true
  github-to-slack-map:
    description: 'Mapping of GitHub usernames to Slack user IDs in JSON format'
    required: true

runs:
  using: 'node20'
  main: 'dist/main.js'
